put config and generated terrain of world in shared directory

diff --git a/nargen b/nargen
--- a/nargen
+++ b/nargen
@@ -1,8 +1,9 @@
 #!/bin/bash
 
 ConfigureNewWorld() {
-    cp -r res/sample_worlds/$2/ configs/$1/
-    echo New world saved at configs/$1/
+    cp -r res/sample_worlds/$2/ worlds/$1/
+    mkdir -p worlds/$1/GENERATED/chunks/ worlds/$1/GENERATED/images/
+    echo New world saved at worlds/$1/
 }
 
 if [ $# -eq 1 ] && [[ "$1" == "--help" || "$1" == "-h" ]] || [ $# -eq 0 ]; then
@@ -12,7 +13,7 @@ if [ $# -eq 1 ] && [[ "$1" == "--help" || "$1" == "-h" ]] || [ $# -eq 0 ]; then
 
 elif [[ $# -eq 3 && "$1" == "new-world" ]]; then
 
-    if [ -d "configs/$2/" ]; then
+    if [ -d "worlds/$2/" ]; then
         echo "Error: A world named $2 already exists"
         exit 1
     elif [ ! -d "res/sample_worlds/$3/" ]; then
@@ -31,8 +32,8 @@ elif [[ $# -eq 2 && "$1" == "generate" ]]; then
     if [ $# -lt 2 ]; then
         echo "Invalid arguments: No config file specified"
         cat res/help_page.txt
-    elif [ -d "configs/$2/" ]; then
-        rm -r -f worlds/$2/
+    elif [ -d "worlds/$2/" ]; then
+        nargen empty-world $2
         if [ $# -ge 3 ]; then
             if [ $3 == "--no-rendering" ]; then
                 node main.js generate $2 0
@@ -49,13 +50,27 @@ elif [[ $# -eq 2 && "$1" == "generate" ]]; then
         exit 1
     fi
 
+elif [[ $# -ge 1 && "$1" == "empty-world" ]]; then
+
+    if [ $# -lt 2 ]; then
+        echo "Invalid arguments: No world name specified"
+        cat res/help_page.txt
+    elif [ -d "worlds/$2/" ]; then
+        rm -rf worlds/$2/GENERATED/*
+        mkdir worlds/$2/GENERATED/chunks/ worlds/$2/GENERATED/images/
+        echo "Emptied world $2"
+    else
+        echo "Error: Cannot find world named $2"
+        exit 1
+    fi
+
 elif [[ $# -ge 1 && "$1" == "delete-world" ]]; then
 
     if [ $# -lt 2 ]; then
         echo "Invalid arguments: No world name specified"
         cat res/help_page.txt
-    elif [ -d "configs/$2" ]; then
-        rm -r -f configs/$2
+    elif [ -d "worlds/$2/" ]; then
+        rm -rf worlds/$2/
         echo "Deleted world $2"
     else
         echo "Error: Cannot find world named $2"
@@ -69,9 +84,9 @@ elif [[ $# -eq 2 && "$1" == "build" ]]; then
 elif [[ $# -eq 2 && "$1" == "render" ]]; then
 
     if [ -d "worlds/$2/" ]; then
-        if [ -f "worlds/$2/WORLD_INFO.json" ]; then
+        if [ -f "worlds/$2/GENERATED/WORLD_INFO.json" ]; then
             python3 main.py render $2
-            viewnior worlds/$2/images/game.png > /dev/null 2>&1
+            viewnior worlds/$2/GENERATED/images/game.png > /dev/null 2>&1
         else
             echo "Error: A world named $2 is found but is not fully rendered. Execute 'nargen generate $2' to generate the world."
         fi
@@ -83,10 +98,7 @@ elif [[ $# -eq 2 && "$1" == "render" ]]; then
 elif [[ $# -eq 2 && "$1" == "view" ]]; then
 
     if [ -d "worlds/$2/" ]; then
-        viewnior worlds/$2/images/ > /dev/null 2>&1
-    elif [ -d "configs/$2/" ]; then
-        echo "Error: $2 has not yet been generated"
-        nargen generate $2
+        viewnior worlds/$2/GENERATED/images/ > /dev/null 2>&1
     else
         echo "Error: Cannot find world named $2."
         exit 1
@@ -94,7 +106,7 @@ elif [[ $# -eq 2 && "$1" == "view" ]]; then
 
 elif [[ $# -eq 1 && "$1" == "list" ]]; then
 
-    ls configs/
+    ls worlds/
 
 elif [[ $# -eq 1 && "$1" == "list-sample-worlds" ]]; then
 
